#!/bin/sh
CURDIR="$(cd $(dirname "$0"); pwd -P)"
DOCKERTAG="operating-systems-1920-pintos"
DOCKERMOUNT="/home/pintos/pintos"

docker build -t "$DOCKERTAG" "$CURDIR/environment"
docker run --rm -it -v "$CURDIR:$DOCKERMOUNT" -v "$HOME/.ssh/id_rsa:/home/pintos/.ssh/id_rsa" -t "$DOCKERTAG"
